(source melpa)
(source org)

(depends-on "request-deferred")
(depends-on "org-plus-contrib")

(package-file "zotxt.el")

(files "zotxt.el" "org-zotxt.el" "zotxt-easykey.el")

(development
  (depends-on "ert-runner")
  (depends-on "ecukes")
  (depends-on "undercover"))
