(source melpa)

(depends-on "request")
(depends-on "deferred")

(package-file "zotxt.el")

(files "zotxt.el" "org-zotxt.el")

(development
  (depends-on "ert-runner")
  (depends-on "ecukes")
  (depends-on "undercover"))
