(source melpa)

(depends-on "request-deferred")

(package-file "zotxt.el")

(files "zotxt.el" "org-zotxt.el" "zotxt-easykey.el")

(development
  (depends-on "ert-runner")
  (depends-on "ecukes")
  (depends-on "undercover"))
