#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'rst2pdf==0.16','console_scripts','rst2pdf'
__requires__ = 'rst2pdf==0.16'
import sys
from pkg_resources import load_entry_point
from docutils.parsers.rst import directives
from zotero import ZoteroDirective, ZoteroSetupDirective

directives.register_directive('zotero', ZoteroDirective)
directives.register_directive('zotero_setup', ZoteroSetupDirective)

if __name__ == '__main__':
    sys.exit(
        load_entry_point('rst2pdf==0.16', 'console_scripts', 'rst2pdf')()
    )
