#!/usr/bin/python

# $Id: rst2odt.py 5839 2009-01-07 19:09:28Z dkuhlman $
# Author: Dave Kuhlman <dkuhlman@rexx.com>
# Copyright: This module has been placed in the public domain.

"""
A front end to the Docutils Publisher, producing OpenOffice documents.
"""

import sys
try:
    import locale
    locale.setlocale(locale.LC_ALL, '')
except:
    pass

from docutils.core import publish_cmdline_to_binary, default_description
from docutils.writers.odf_odt import Writer, Reader, ODFTranslator, SubElement
from docutils.parsers.rst import directives
from docutils.writers import Writer as WriterBase

from zotero import ZoteroDirective, ZoteroSetupDirective

directives.register_directive('zotero', ZoteroDirective)
directives.register_directive('zotero_setup', ZoteroSetupDirective)

description = ('Generates OpenDocument/OpenOffice/ODF documents from '
               'standalone reStructuredText sources.  ' + default_description)

class ODFTranslatorWithSmallCaps(ODFTranslator):

    def visit_smallcaps(self, node):
        el = SubElement(self.current_element, 'text:span',
            attrib={'text:style-name': 'rststyle-small-caps'})
        self.set_current_element(el)

    def depart_smallcaps(self, node):
        self.set_to_parent()

class WriterWithSmallCaps(Writer):
    def __init__(self):
        WriterBase.__init__(self)
        self.translator_class = ODFTranslatorWithSmallCaps

writer = WriterWithSmallCaps()
reader = Reader()
output = publish_cmdline_to_binary(reader=reader, writer=writer,
    description=description)

